---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ttrss-pv
spec:
  storageClassName: gluster-vol-default
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/general-volume/ttrss"