apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-vol-default
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.0.89:80"
  restuser: ""
  secretNamespace: ""
  secretName: ""
allowVolumeExpansion: true