apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-rss-db-deployment
spec:
  selector:
    matchLabels:
      app: tt-rss
  replicas: 1
  template:
    metadata:
      labels:
        app: tt-rss
    spec:
      containers:
      - name: db
        image: postgres:12-alpine
        imagePullPolicy: Always
        volumeMounts:
          - name: db-vol
            mountPath: /var/lib/postgresql/data
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: postgres
      volumes:
      - name: db-vol
        persistentVolumeClaim:
          claimName: local-path-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
  labels:
    run: tt-rss
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: tt-rss

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pgsql-service
# spec:
#   selector:
#     app: tt-rss
#   ports:
#     - protocol: TCP
#       port: 5432
#       targetPort: 5432
