---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ajvcorreia/ttrss-web_nginx
        imagePullPolicy: Always
        volumeMounts:
          - name: nginx-vol2
            mountPath: /var/www/html
        ports:
        - containerPort: 80
        env:
        - name: SELF_URL_PATH
          value: "http://192.168.0.89:8080/tt-rss"
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: pgsql-config
              key: http-port
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: pgsql-config
              key: app-url
      volumes:
      - name: nginx-vol2
        persistentVolumeClaim:
          claimName: local-path-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: web-nginx
#   labels:
#     run: nginx
# spec:
#   selector:    
#     app: nginx
#   ports:  
#   - name: http
#     port: 80
#     targetPort: 80
#     protocol: TCP
#   type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer