apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ajvcorreia/ttrss-web_nginx
        imagePullPolicy: Always
        volumeMounts:
          - name: nginx-vol
            mountPath: /var/www/html
        ports:
        - containerPort: 80
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: pgsql-config
              key: http-port
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: pgsql-config
              key: app-url
      volumes:
      - name: nginx-vol
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx
  labels:
    run: nginx
spec:
  selector:    
    app: nginx
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP